Fix PHPCS errors, add PHPMD
monsieurbiz/SyliusNoCommercePlugin pull request #17
Opened 2021-09-27 15:24 UTC by delyriand

2021-09-27 20:59 UTC, jacquesbh requested changes
The merge commit should not be there.

2021-09-30 20:16 UTC, jacquesbh approved these changes

2021-10-01 07:31 UTC, lanfisis approved these changes

2021-10-01 07:33 UTC, lanfisis commented
Thank you dude 👍

2021-10-01 07:33 UTC, merged