Improve recipe 1.0
monsieurbiz/SyliusNoCommercePlugin pull request #21
Opened 2021-09-28 13:58 UTC by delyriand

Copy template from package and display post install instructions:

![image](https://user-images.githubusercontent.com/465524/135101500-b74d7ec6-62ba-413f-9c00-f1cef4e16100.png)

2021-09-28 20:00 UTC, jacquesbh requested changes

2021-09-28 20:00 UTC, jacquesbh commented on recipes/1.0/post-install.txt
> +    <error>-     use MicroKernelTrait;</error>
```suggestion
    <fg=#c0392b>-     use MicroKernelTrait;</>
```

2021-09-28 20:00 UTC, jacquesbh commented on recipes/1.0/post-install.txt
> +  * Add some annotations to your <info>src/Entity/Channel/Channel.php</info> entity to prevent error during Channel saving:
```suggestion
  * Add these annotations to your <info>src/Entity/Channel/Channel.php</info> entity to prevent errors during Channel saving:
```

2021-09-29 12:49 UTC, delyriand commented on recipes/1.0/post-install.txt
> +    <error>-     use MicroKernelTrait;</error>
i use `fg=red` because the hex color code is not interpreted.  
PS: I replace other `<info>` by `<fg=green>` for the code diff

2021-09-29 14:53 UTC, jacquesbh approved these changes

2021-09-29 14:54 UTC, delyriand commented on recipes/1.0/post-install.txt
> +    <comment>./bin/console doctrine:migrations:diff
remove the diff

2021-09-30 20:17 UTC, jacquesbh approved these changes

2021-09-30 20:17 UTC, merged

2021-09-30 20:17 UTC, jacquesbh commented
Thank you @delyriand !